Feat/restricao alimentar
muralis-labs/jane-api pull request #33
Opened 2024-02-05 00:02 UTC by dantemds

2024-02-06 21:15 UTC, pablowinck requested changes

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/core/mapper/ColaboradorJuridicoMapper.java
>  public interface ColaboradorJuridicoMapper {
Para essa interface, considere os mesmos comentários dessa:
src/main/java/br/com/muralis/core/mapper/ColaboradorFisicoMapper.java

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/core/mapper/RestricaoAlimentarMapper.java
> +public interface RestricaoAlimentarMapper {
formatar código

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/core/objectValue/DadosBancarios.java
> +public class DadosBancarios {
formatar código

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/core/objectValue/DadosBancarios.java
> +package br.com.muralis.core.objectValue;
pattern do java é `objectvalue` tudo minusculo...

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/core/usecase/restricaoAlimentar/BuscarRestricaoPorTermo.java
> +public class BuscarRestricaoPorTermo {
formatar código

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/core/usecase/restricaoAlimentar/BuscarRestricaoPorTermo.java
> +        Log.info("Lista de restrições alimentares foi montada");
Sempre manter fluxo de logs, para facilitar na hora do rastreio.
#### O que isso significa?
Basicamente os parâmetros de entrada devem estar presentes em todos os logs.
Como você adicionou na linha 16 `Log.info("Preparando para buscar restrição alimentar por termo: " + termo);` mantém na linha 18 o parâmetro "termo", ficando assim:
```suggestion
        Log.info("{} restrições alimentares encontradas a partir do termo: {}", restricaoAlimentarList, termo);
```

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/core/usecase/restricaoAlimentar/BuscarRestricaoPorTermo.java
> +        List<RestricaoAlimentar> restricaoAlimentarList = repository.findByTerm(termo);
Substitua por um nome menos ambiguo, como por exemplo: restricoesAlimentares.
#### Qual o problema de botar "list" no final?
Considere que tudo que fazemos no código, vira "padrão" no futuro. Logo, para um cenário que estou lidando com altura por exemplo, a variável ficaria float alturaFloat, e o nome de um colaborador, String colaboradorString

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/core/usecase/restricaoAlimentar/CadastrarRestricaoAlimentar.java
> +public class CadastrarRestricaoAlimentar {
formatar código

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/core/usecase/restricaoAlimentar/CadastrarRestricaoAlimentar.java
> +        Log.info("Restrição alimentar salva: " + restricaoAlimentar.getId());
Cuidar com fluxo de logs... como exibiu o nome anteriormente, tem que exibir nesse log também.

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/inbound/controller/RestricaoAlimentarController.java
> +    @Operation(summary = "Esse é usado para buscar restrições alimentares por termo", description = "Retorna uma lista de restrições alimentares")
```suggestion
    @Operation(summary = "Busca restrições alimentares por termo", description = "Retorna uma lista de restrições alimentares")
```

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/inbound/controller/RestricaoAlimentarController.java
> +    @Operation(summary = "Esse é usado para criar uma restrição alimentar", description = "Retorna a restrição alimentar criada")
```suggestion
    @Operation(summary = "Criar uma restrição alimentar", description = "Retorna a restrição alimentar criada")
```

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/inbound/controller/RestricaoAlimentarController.java
> +    }
formatar código

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/outbound/hibernate/mapper/PanacheRestricaoAlimentarMapper.java
> +public interface PanacheRestricaoAlimentarMapper {
formatar código

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/outbound/hibernate/objectValue/DadosBancarios.java
> +public class DadosBancarios {
formatar código

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/outbound/hibernate/repository/RestricaoAlimentarPanacheRepository.java
> +public class RestricaoAlimentarPanacheRepository implements RestricaoAlimentarRepository {
formatar código

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/outbound/hibernate/table/PanacheColaborador.java
> +	@ManyToMany
formatar código

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/outbound/hibernate/table/PanacheColaborador.java
> +	@JoinTable(name="colaborador_tem_restricoes", joinColumns=
Não sei se concordo muito com esse padrão de nomenclatura...
Não acha mais correto algo como: restricoes_colaborador?

2024-02-06 21:15 UTC, pablowinck commented on src/main/java/br/com/muralis/outbound/hibernate/table/PanacheRestricaoAlimentar.java
> +public class PanacheRestricaoAlimentar extends PanacheEntityBase {
formatar código

2024-02-06 21:15 UTC, pablowinck commented on src/test/java/br/com/muralis/core/usecase/colaborador/fisico/AtualizarColaboradorFisicoTest.java
> +	@TestTransaction
se anotar na clase, será que não resolve para todos métodos?

2024-02-06 21:15 UTC, pablowinck commented on src/test/java/br/com/muralis/core/usecase/colaborador/fisico/ListarColaboradoresFisicoTest.java
> +					.email("colaborador" + i + UUID.randomUUID() + "@muralis.com.br")
É interessante você olhar para todos testes de listagem e "guardar" esses UUID's.
Pois no retorno, é interessante fazer um .filter nos UUID's criados.
Eu gosto da tratativa de ter só 1 UUID por teste, e esse a gente faz o filter na hora do assert.

2024-02-06 21:15 UTC, pablowinck commented on src/test/java/br/com/muralis/core/usecase/restricaoAlimentar/CadastrarRestricaoAlimentarTest.java
> +public class CadastrarRestricaoAlimentarTest {
formatar código

2024-02-07 13:27 UTC, dantemds commented on src/test/java/br/com/muralis/core/usecase/colaborador/fisico/AtualizarColaboradorFisicoTest.java
> +	@TestTransaction
Não podemos anotar a classe porque ele faria rollback no beforeEach

2024-03-05 21:52 UTC, pablowinck requested changes

2024-03-05 21:52 UTC, pablowinck commented on src/main/java/br/com/muralis/core/mapper/ColaboradorFisicoMapper.java
> +	@Mapping(target = "restricoesAlimentares", source = "restricoesAlimentares")
retirar linha

2024-03-05 21:52 UTC, pablowinck commented on src/main/java/br/com/muralis/core/mapper/ColaboradorFisicoMapper.java
> +	default List<RestricaoAlimentar> from(List<String> ids) {
1. Refatorar para utilizar Optional
```java
return Optional.ofNullable(ids)
			.filter((identificadores) -> !identificadores.isEmpty())
			.map((identificadores) -> identificadores.stream()
				.map((id) -> RestricaoAlimentar.builder().id(id).build())
				.toList())
			.orElse(Collections.emptyList());
```

2. Criar testes unitários

2024-03-05 21:52 UTC, pablowinck commented on src/main/java/br/com/muralis/core/usecase/restricaoAlimentar/CadastrarRestricaoAlimentar.java
> +	public RestricaoAlimentar execute(CadastrarRestricaoAlimentarCommand command) {
Invalidar cache ao cadastrar

2024-03-05 21:52 UTC, pablowinck commented on src/main/java/br/com/muralis/inbound/configuration/CacheClearer.java
> +public class CacheClearer {
Deletar esse arquivo, ou se é necessário nos testes, mover para classe de teste

2024-03-05 21:52 UTC, pablowinck commented on src/main/java/br/com/muralis/inbound/configuration/CacheConfigManager.java
> +public class CacheConfigManager {
Deletar esse arquivo, ou se é necessário nos testes, mover para classe de teste

2024-03-05 21:52 UTC, pablowinck commented on src/main/java/br/com/muralis/outbound/hibernate/mapper/PanacheRestricaoAlimentarMapper.java
> +	default String normalize(String nome) {
Criar teste unitário

2024-03-05 21:52 UTC, pablowinck commented on src/test/java/br/com/muralis/core/usecase/restricaoAlimentar/BuscarRestricaoAlimentarPorTermoTest.java
> +		assertTrue(result2 < 50);
Retirar essa linha, pois favorece erros na pipeline

2024-03-07 13:16 UTC, pablowinck requested changes

2024-03-07 13:16 UTC, pablowinck commented on src/main/java/br/com/muralis/core/mapper/ColaboradorJuridicoMapper.java
> +	default Empresa from(String id) {
Ele já faz o mapeamento da empresa por conta de estar usando o EmpresaRepository

2024-03-07 13:16 UTC, pablowinck commented on src/main/java/br/com/muralis/core/usecase/restricaoAlimentar/BuscarRestricaoPorTermo.java
> +package br.com.muralis.core.usecase.restricaoAlimentar;
renomear pacote para `restricaoalimentar`

2024-03-07 18:50 UTC, dantemds commented on src/main/java/br/com/muralis/core/mapper/ColaboradorJuridicoMapper.java
> +	default Empresa from(String id) {
Se tirar não funciona, então criei um teste

2024-03-12 12:15 UTC, pablowinck requested changes

2024-03-12 12:15 UTC, pablowinck commented on src/main/java/br/com/muralis/core/dto/Documento.java
> +public class Documento {
```suggestion
public class Documento {

```

2024-03-12 12:15 UTC, pablowinck commented on src/main/java/br/com/muralis/core/usecase/restricaoalimentar/BuscarRestricaoPorTermo.java
> +		Log.info("Lista de restrições alimentares foi montada");
Sempre mantém um fluxo de logs, se você mostrou o termo no log de cima, no de baixo precisa mostrar também. Pense em milhares de logs acontecendo ao mesmo tempo, fica difícil rastrear se não mantermos um fluxo adequado

2024-03-12 12:15 UTC, pablowinck commented on src/main/java/br/com/muralis/core/usecase/restricaoalimentar/CadastrarRestricaoAlimentar.java
> +		Log.info("Restrição alimentar salva: " + restricaoAlimentar.getId());
Nos logs anteriores você mostrou o nome, se aqui quer mostrar o id também, tudo bem, porém precisa mostrar o nome também.

2024-03-12 12:15 UTC, pablowinck commented on src/main/java/br/com/muralis/inbound/controller/ColaboradorFisicoController.java
Em declaração de atributo/método, o padrão é sempre só um espaço

2024-03-12 21:53 UTC, pablowinck requested changes

2024-03-12 21:53 UTC, pablowinck commented on src/main/java/br/com/muralis/inbound/controller/RestricaoAlimentarController.java
> +	@Path("/{termo}")
Normalmente buscas por termo são por RequestParm e não PathParm.
### como assim?
O comportamento esperado é:
- se chamo /v1/restricoes-alimentares, espero:
  - 1: Que retorne uma lista com todas restricoes alimentares
  - 2: Que retorne uma lista paginada
  - 3: Que retorne que um parâmetro termo é obrigatório
- O correto é /v1/restricoes-alimentares?termo=

2024-03-12 21:53 UTC, pablowinck commented on src/main/java/br/com/muralis/inbound/controller/RestricaoAlimentarController.java
> +@Path("/v1/restricaoalimentar")
```suggestion
@Path("/v1/restricoes-alimentares")
```

2024-03-12 21:53 UTC, pablowinck commented on src/main/java/br/com/muralis/outbound/hibernate/repository/RestricaoAlimentarPanacheRepository.java
> +					"%" + Normalizer.normalize(termo, Normalizer.Form.NFD).replaceAll("[^\\p{ASCII}]", "").toUpperCase()
Como você usa esse normalizer com esses parametros em várias partes do código, não acha que vale criar uma domain service que faça essa função?
*Exemplo:*
```java
public class TextNormalizer {

  public static String execute(String denormalizedValue) {
    return Normalizer.normalize(denormalizedValue, Normalizer.Form.NFD).replaceAll("[^\\p{ASCII}]", "");
  }

}
```

2024-03-12 21:53 UTC, pablowinck commented on src/main/java/br/com/muralis/outbound/hibernate/table/PanacheRestricaoAlimentar.java
> +	public List<PanacheColaborador> colaboradorList;
`colaboradorList` é redundante

2024-03-12 21:53 UTC, pablowinck commented on src/test/java/br/com/muralis/core/mapper/ColaboradorFisicoMapperTest.java
> +	@Inject
```suggestion

	@Inject
```

2024-03-12 21:53 UTC, pablowinck commented on src/main/java/br/com/muralis/outbound/hibernate/repository/RestricaoAlimentarPanacheRepository.java
> +					"%" + Normalizer.normalize(termo, Normalizer.Form.NFD).replaceAll("[^\\p{ASCII}]", "").toUpperCase()
Ah... não esqueça de adicionar testes unitários nesse caso.
Aliás, é um ótimo caso para testes parametrizados!

2024-03-15 11:59 UTC, pablowinck approved these changes

2024-03-17 00:07 UTC, merged